table Dim_Date
	lineageTag: 623f2bbd-cc93-4c0a-a311-77469290b291

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0fb4f59-fc9f-4277-820e-993e63efcf4f
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: f8fc79a6-5512-476b-9689-6ec8dc8a5ec0
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: 0
		lineageTag: d6f6ac8d-433d-4b24-8ef3-6d67dccce7e2
		summarizeBy: sum
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: d9d92f6f-8ebf-4f41-a517-4d3a7eb5398b
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 1686e89d-49ac-454f-9cdf-2d77a43be64c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2035, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    AsTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
				    Typed = Table.TransformColumnTypes(AsTable, {{"Date", type date}}),
				    AddYear = Table.AddColumn(Typed, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonthNo = Table.AddColumn(AddYear, "MonthNo", each Date.Month([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddMonthNo, "Month", each Date.ToText([Date], "MMMM"), type text),
				    AddQuarter = Table.AddColumn(AddMonth, "Quarter", each "Q" & Number.ToText(Date.QuarterOfYear([Date])), type text)
				in
				    AddQuarter

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

